# fly.toml app configuration file generated for portfolio-appez on 2025-09-29T16:10:52+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'portfolio-appez'
primary_region = 'ams'
console_command = '/code/manage.py shell'

[build]

[deploy]
  release_command = "python manage.py migrate"

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
