# Generated by Django 5.2.6 on 2025-09-23 13:37

import django.db.models.deletion
import portfolio.storage_backends
import utils.nameHandler
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, storage=portfolio.storage_backends.ProjectImagesStorage(), upload_to=utils.nameHandler.rename_file_to_upload)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('github_link', models.URLField(blank=True, null=True)),
                ('live_link', models.URLField(blank=True, null=True)),
                ('images', models.ManyToManyField(blank=True, related_name='projects', to='project.image')),
                ('placeholder_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placeholder_for', to='project.image')),
                ('tags', models.ManyToManyField(related_name='projects', to='project.tag')),
            ],
        ),
    ]
