# Generated by Django 5.2.6 on 2025-10-05 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='linked_projects',
            field=models.ManyToManyField(blank=True, to='project.project'),
        ),
    ]
