# Generated by Django 5.2.6 on 2026-01-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_linked_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='legend',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
